package com.classeschedule.widget;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.Gravity;import android.widget.*;import org.json.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout list; int day=0; final String[] days={"Monday","Tuesday","Wednesday","Thursday","Friday"};
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);list=findViewById(R.id.listContainer);Button[] bs={findViewById(R.id.dayMon),findViewById(R.id.dayTue),findViewById(R.id.dayWed),findViewById(R.id.dayThu),findViewById(R.id.dayFri)};for(int i=0;i<5;i++){final int d=i;bs[i].setOnClickListener(v->{day=d;refresh();});}findViewById(R.id.addButton).setOnClickListener(v->edit(-1));day=Math.max(0,Math.min(4,Calendar.getInstance().get(Calendar.DAY_OF_WEEK)-Calendar.MONDAY));refresh();}
 JSONArray data(){try{return new JSONArray(getSharedPreferences("schedule",0).getString("classes","[]"));}catch(Exception e){return new JSONArray();}}
 void save(JSONArray a){getSharedPreferences("schedule",0).edit().putString("classes",a.toString()).apply();sendBroadcast(new Intent(this,ScheduleWidgetProvider.class).setAction("com.classeschedule.widget.UPDATE"));}
 void refresh(){((TextView)findViewById(R.id.dayTitle)).setText(days[day]);list.removeAllViews();JSONArray a=data();for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);if(o.optInt("day")!=day)continue;final int n=i;LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(14,10,14,10);TextView t=new TextView(this);t.setText(o.optString("subject")+"  •  "+o.optString("time"));t.setTextColor(Color.WHITE);t.setTextSize(16);TextView s=new TextView(this);s.setText(o.optString("room")+"   "+o.optString("teacher"));s.setTextColor(Color.GRAY);s.setTextSize(12);r.addView(t);r.addView(s);r.setOnClickListener(v->edit(n));list.addView(r);}catch(Exception e){}if(list.getChildCount()==0){TextView e=new TextView(this);e.setText("No classes yet. Tap + ADD CLASS.");e.setTextColor(Color.GRAY);e.setPadding(8,25,8,25);list.addView(e);}}
 void edit(int idx){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText sub=new EditText(this);sub.setHint("Subject");EditText time=new EditText(this);time.setHint("Start time, e.g. 7:30 AM");EditText room=new EditText(this);room.setHint("Room");EditText teacher=new EditText(this);teacher.setHint("Teacher");box.addView(sub);box.addView(time);box.addView(room);box.addView(teacher);JSONArray a=data();if(idx>=0)try{JSONObject o=a.getJSONObject(idx);sub.setText(o.optString("subject"));time.setText(o.optString("start"));room.setText(o.optString("room"));teacher.setText(o.optString("teacher"));}catch(Exception e){}AlertDialog d=new AlertDialog.Builder(this).setTitle(idx<0?"Add class":"Edit class").setView(box).setPositiveButton("Save",(x,w)->{try{JSONObject o=idx<0?new JSONObject():a.getJSONObject(idx);o.put("day",day);o.put("subject",sub.getText().toString().trim());o.put("start",time.getText().toString().trim());o.put("time",time.getText().toString().trim());o.put("room",room.getText().toString().trim());o.put("teacher",teacher.getText().toString().trim());if(idx<0)a.put(o);save(a);refresh();}catch(Exception e){}}).setNegativeButton("Cancel",null).create();if(idx>=0)d.setButton(AlertDialog.BUTTON_NEUTRAL,"Delete",(x,w)->{JSONArray n=data();n.remove(idx);save(n);refresh();});d.show();}
}
